// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://rgjxpfaofwchxqbpfwow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnanhwZmFvZndjaHhxYnBmd293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDI5MjQsImV4cCI6MjA2OTY3ODkyNH0.rvRdBB5Un3ChDk2LoTmvArt_SNOLQ_9_fnGt6C-2XeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
